"""GENERATED by tools/gen_gs_fields.py from a gs 1.5.4 signature snapshot. Do not hand-edit (IMPLEMENTATION_PLAN.md section 0.2).

Not yet implemented: see IMPLEMENTATION_PLAN.md for the phase that fills this in.
"""
