"""Generate src/pricebt/instrument/_gs_fields.py from tests/data/gs_instruments_1_5_4.json
(IMPLEMENTATION_PLAN.md P1.6; DESIGN.md section 5.1).

Run with the stir env's python (this tool imports nothing from gs_quant; it only reads the JSON
snapshot that tools/gs_api_snapshot.py already wrote with the base python):

    C:\\Users\\chris\\anaconda3\\envs\\stir\\python.exe tools\\gen_gs_fields.py

Writes src/pricebt/instrument/_gs_fields.py for exactly the classes in CLASS_LIST below. That file
is GENERATED -- never hand-edit it (IMPLEMENTATION_PLAN.md section 0.2); re-run this tool instead.

`coerce_tag` is the pricebt.common enum class NAME (a string) when a gs field's annotation string
is `typing.Optional[<EnumClass>]` and `<EnumClass>` is in PRICEBT_ENUM_NAMES below, else None.

`default_repr` is `repr(gs_default)`, taken as-is from gs_api_snapshot.py's JSON. For the current
8 mirrored classes every field default is `None`/`0.0` (a real Python literal), so `default_repr`
is always directly embeddable source text. That is NOT guaranteed for an enum-valued gs default: an
enum's `repr()` (e.g. `<PayReceive.pay: 'Pay'>`) is not valid Python once re-embedded as a bare
literal, and `repr()` of a `default_factory` field would be a callable's repr, not a value at all
-- gs_api_snapshot.py now reports those as the literal string "FACTORY" rather than a callable
repr. Neither case is exercised today; a future class added to CLASS_LIST with such a field needs
this generator taught to special-case it.
PRICEBT_ENUM_NAMES is copied verbatim from IMPLEMENTATION_PLAN.md's P1.1 task (the "Build" list of
enum names) -- this module MUST NOT `import pricebt.common`, because P1.1 writes that module in a
parallel task that may not have finished yet. tests/test_gen_gs_fields.py cross-checks this literal
list against the real `pricebt.common` enum set once P1.1 exists.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_JSON = ROOT / "tests" / "data" / "gs_instruments_1_5_4.json"
OUT_PY = ROOT / "src" / "pricebt" / "instrument" / "_gs_fields.py"

# The classes _gs_fields.py mirrors (DESIGN.md decision 0.6: a later gs class is added by adding
# its name here and regenerating -- a data change, not hand-written code). This order is also the
# order the classes appear in the generated file.
CLASS_LIST = ["IRSwap", "IRSwaption", "FXOption", "FXForward", "EqOption", "InflationSwap", "Cash", "Bond"]

# Copied verbatim from IMPLEMENTATION_PLAN.md's P1.1 task ("Enums declared as class X(EnumBase,
# str, Enum)"). Do NOT `import pricebt.common` here -- see the module docstring.
PRICEBT_ENUM_NAMES = [
    "PayReceive", "BuySell", "AggregationLevel", "OptionType", "OptionStyle",
    "DayCountFraction", "BusinessDayConvention", "SwapClearingHouse", "PrincipalExchange",
    "SwapSettlement", "AccrualConvention",
    "UnderlierType", "TradeAs", "OptionSettlementMethod", "OptionExerciseStyle", "RiskMeasureUnit",
    "AssetClass", "AssetType", "CurrencyName", "PositionType",
    "Currency",
    "FiniteDifferenceMethod",  # IR_RISK_DESIGN.md section 1.4 (no instrument field uses it)
]

_OPTIONAL_RE = re.compile(r"^typing\.Optional\[([\w.]+)\]$")


def coerce_tag_for(annotation: str) -> str | None:
    """`annotation` is the annotation_str the snapshot recorded, e.g.
    'typing.Optional[gs_quant.target.common.PayReceive]' -> 'PayReceive', or None when the
    annotation is not `Optional[<single dotted name>]`, or when that name isn't a pricebt enum."""
    m = _OPTIONAL_RE.match(annotation)
    if not m:
        return None
    enum_name = m.group(1).rsplit(".", 1)[-1]
    return enum_name if enum_name in PRICEBT_ENUM_NAMES else None


def build_class_entry(raw: dict) -> dict:
    """`raw` is one class's entry from gs_instruments_1_5_4.json: {'asset_class', 'type_',
    'fields': [[name, init, default_repr, annotation_str], ...]} (ALL dataclass fields, in
    declaration order). Keep only the init=True fields, in the same order, dropping the static
    asset_class/type_ fields (held separately, as in gs)."""
    fields = [(name, default_repr, coerce_tag_for(annotation))
              for name, init, default_repr, annotation in raw["fields"] if init]
    return {"asset_class": raw["asset_class"], "type_": raw["type_"], "fields": fields}


def render(classes: dict) -> str:
    lines = [
        "# generated by tools/gen_gs_fields.py from gs_quant 1.5.4 — do not edit",
        '"""Per-class gs_quant 1.5.4 field data for pricebt.instrument (DESIGN.md section 5.1).',
        "",
        "GS_FIELDS[class_name] = {'asset_class': <repr str>, 'type_': <repr str>,",
        "                         'fields': [(field_name, default_repr, coerce_tag), ...]}",
        "",
        "`fields` is in gs __init__ order. `default_repr` is `repr(gs_default)` -- for every field",
        "below (a plain None/0.0/str/int default) that is literal Python source text, directly",
        "embeddable in a generated `def __init__` signature. It is NOT guaranteed to be for an",
        "enum-valued or default_factory-valued gs default (none exist among these classes' fields",
        "today); see tools/gen_gs_fields.py's module docstring. `coerce_tag` is a pricebt.common",
        "enum class name, or None when the field is not enum-tagged.",
        '"""',
        "from __future__ import annotations",
        "",
        "GS_FIELDS: dict = {",
    ]
    for name in CLASS_LIST:
        entry = classes[name]
        lines.append(f"    {name!r}: {{")
        lines.append(f"        'asset_class': {entry['asset_class']!r},")
        lines.append(f"        'type_': {entry['type_']!r},")
        lines.append("        'fields': [")
        for fname, default_repr, coerce_tag in entry["fields"]:
            lines.append(f"            ({fname!r}, {default_repr!r}, {coerce_tag!r}),")
        lines.append("        ],")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_source() -> str:
    data = json.loads(SRC_JSON.read_text(encoding="utf8"))
    dataclasses_ = data["dataclasses"]
    missing = [n for n in CLASS_LIST if n not in dataclasses_]
    if missing:
        raise SystemExit(f"gen_gs_fields.py: {missing} not found in {SRC_JSON}; "
                          f"run tools/gs_api_snapshot.py first")
    classes = {name: build_class_entry(dataclasses_[name]) for name in CLASS_LIST}
    return render(classes)


def main() -> None:
    source = generate_source()
    OUT_PY.write_text(source, encoding="utf8", newline="\n")
    print(f"wrote {OUT_PY} ({len(CLASS_LIST)} classes)")


if __name__ == "__main__":
    main()
