"""Generate `.claude/skills/<name>/SKILL.md` stubs from `skills/<name>/SKILL.md`.

Claude Code discovers project skills in `.claude/skills/`; the canonical, tool-neutral skills live in
`skills/`. Each stub carries the same frontmatter (so skill matching works) and points to the real file.

    python tools/sync_agent_skills.py          # write/refresh stubs, delete stale ones
    python tools/sync_agent_skills.py --check  # exit 1 if the mirror is out of date (used by the tests)
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import Dict, Tuple

import yaml

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"
MIRROR = ROOT / ".claude" / "skills"
MARKER = "<!-- generated by tools/sync_agent_skills.py from skills/{name}/SKILL.md - do not edit; edit the source and re-run -->"


def read_frontmatter(path: Path) -> Tuple[Dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: no YAML frontmatter")
    end = text.index("\n---", 4)
    meta = yaml.safe_load(text[4:end]) or {}
    return meta, text[end + 4:]


def stub_text(name: str, description: str) -> str:
    front = yaml.safe_dump({"name": name, "description": description}, sort_keys=False, allow_unicode=True, width=10_000).strip()
    return (
        f"---\n{front}\n---\n\n{MARKER.format(name=name)}\n\n"
        f"This skill lives at `skills/{name}/SKILL.md` (from the repository root). Read that file and follow it; "
        f"its relative links resolve from there. Library index: `skills/README.md`.\n"
    )


def expected() -> Dict[str, str]:
    out = {}
    for skill_md in sorted(SKILLS.glob("*/SKILL.md")):
        meta, _ = read_frontmatter(skill_md)
        name = meta["name"]
        out[name] = stub_text(name, meta["description"])
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    want = expected()
    have = {p.parent.name: p.read_text(encoding="utf-8") for p in MIRROR.glob("*/SKILL.md")} if MIRROR.exists() else {}
    drift = sorted(set(want) ^ set(have) | {n for n in want if n in have and want[n] != have[n]})
    if args.check:
        if drift:
            print("out of date:", ", ".join(drift))
            return 1
        print(f"in sync ({len(want)} skills)")
        return 0
    for name in set(have) - set(want):
        shutil.rmtree(MIRROR / name)
    for name, text in want.items():
        target = MIRROR / name / "SKILL.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {len(want)} stubs to {MIRROR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
